version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always

    env_file:
      - ./postgres.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend

    container_name: backend-app

    restart: always

    ports:
      - "4000:4000"

    env_file:
      - ../backend/.env

    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend

    container_name: frontend-app

    restart: always

    ports:
      - "5173:5173"

    env_file:
      - ../frontend/.env

    depends_on:
      - backend

volumes:
  postgres_data:
